import Footer from "@/components/Footer";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <div className="min-h-screen bg-gradient-to-r from-purple-500 via-pink-500 to-red-500">
          <div className="pt-6">
            <Navbar />
          </div>
          {children}
          <div className="pt-6">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
